./states_creator.ps1 -FULL_STATE_NAME "Alabama" -ABBREVIATED_STATE_NAME "AL"
./states_creator.ps1 -FULL_STATE_NAME "Alaska" -ABBREVIATED_STATE_NAME "AK"
./states_creator.ps1 -FULL_STATE_NAME "Arizona" -ABBREVIATED_STATE_NAME "AZ"
./states_creator.ps1 -FULL_STATE_NAME "Arkansas" -ABBREVIATED_STATE_NAME "AR"
./states_creator.ps1 -FULL_STATE_NAME "California" -ABBREVIATED_STATE_NAME "CA"
./states_creator.ps1 -FULL_STATE_NAME "Colorado" -ABBREVIATED_STATE_NAME "CO"
./states_creator.ps1 -FULL_STATE_NAME "Connecticut" -ABBREVIATED_STATE_NAME "CT"
./states_creator.ps1 -FULL_STATE_NAME "Delaware" -ABBREVIATED_STATE_NAME "DE"
./states_creator.ps1 -FULL_STATE_NAME "Florida" -ABBREVIATED_STATE_NAME "FL"
./states_creator.ps1 -FULL_STATE_NAME "Georgia" -ABBREVIATED_STATE_NAME "GA"
./states_creator.ps1 -FULL_STATE_NAME "Hawaii" -ABBREVIATED_STATE_NAME "HI"
./states_creator.ps1 -FULL_STATE_NAME "Idaho" -ABBREVIATED_STATE_NAME "ID"
./states_creator.ps1 -FULL_STATE_NAME "Illinois" -ABBREVIATED_STATE_NAME "IL"
./states_creator.ps1 -FULL_STATE_NAME "Indiana" -ABBREVIATED_STATE_NAME "IN"
./states_creator.ps1 -FULL_STATE_NAME "Iowa" -ABBREVIATED_STATE_NAME "IA"
./states_creator.ps1 -FULL_STATE_NAME "Kansas" -ABBREVIATED_STATE_NAME "KS"
./states_creator.ps1 -FULL_STATE_NAME "Kentucky" -ABBREVIATED_STATE_NAME "KY"
./states_creator.ps1 -FULL_STATE_NAME "Louisiana" -ABBREVIATED_STATE_NAME "LA"
./states_creator.ps1 -FULL_STATE_NAME "Maine" -ABBREVIATED_STATE_NAME "ME"
./states_creator.ps1 -FULL_STATE_NAME "Maryland" -ABBREVIATED_STATE_NAME "MD"
./states_creator.ps1 -FULL_STATE_NAME "Massachusetts" -ABBREVIATED_STATE_NAME "MA"
./states_creator.ps1 -FULL_STATE_NAME "Michigan" -ABBREVIATED_STATE_NAME "MI"
./states_creator.ps1 -FULL_STATE_NAME "Minnesota" -ABBREVIATED_STATE_NAME "MN"
./states_creator.ps1 -FULL_STATE_NAME "Mississippi" -ABBREVIATED_STATE_NAME "MS"
./states_creator.ps1 -FULL_STATE_NAME "Missouri" -ABBREVIATED_STATE_NAME "MO"
./states_creator.ps1 -FULL_STATE_NAME "Montana" -ABBREVIATED_STATE_NAME "MT"
./states_creator.ps1 -FULL_STATE_NAME "Nebraska" -ABBREVIATED_STATE_NAME "NE"
./states_creator.ps1 -FULL_STATE_NAME "Nevada" -ABBREVIATED_STATE_NAME "NV"
./states_creator.ps1 -FULL_STATE_NAME "New Hampshire" -ABBREVIATED_STATE_NAME "NH"
./states_creator.ps1 -FULL_STATE_NAME "New Jersey" -ABBREVIATED_STATE_NAME "NJ"
./states_creator.ps1 -FULL_STATE_NAME "New Mexico" -ABBREVIATED_STATE_NAME "NM"
./states_creator.ps1 -FULL_STATE_NAME "New York" -ABBREVIATED_STATE_NAME "NY"
./states_creator.ps1 -FULL_STATE_NAME "North Carolina" -ABBREVIATED_STATE_NAME "NC"
./states_creator.ps1 -FULL_STATE_NAME "North Dakota" -ABBREVIATED_STATE_NAME "ND"
./states_creator.ps1 -FULL_STATE_NAME "Ohio" -ABBREVIATED_STATE_NAME "OH"
./states_creator.ps1 -FULL_STATE_NAME "Oklahoma" -ABBREVIATED_STATE_NAME "OK"
./states_creator.ps1 -FULL_STATE_NAME "Oregon" -ABBREVIATED_STATE_NAME "OR"
./states_creator.ps1 -FULL_STATE_NAME "Pennsylvania" -ABBREVIATED_STATE_NAME "PA"
./states_creator.ps1 -FULL_STATE_NAME "Rhode Island" -ABBREVIATED_STATE_NAME "RI"
./states_creator.ps1 -FULL_STATE_NAME "South Carolina" -ABBREVIATED_STATE_NAME "SC"
./states_creator.ps1 -FULL_STATE_NAME "South Dakota" -ABBREVIATED_STATE_NAME "SD"
./states_creator.ps1 -FULL_STATE_NAME "Tennessee" -ABBREVIATED_STATE_NAME "TN"
./states_creator.ps1 -FULL_STATE_NAME "Texas" -ABBREVIATED_STATE_NAME "TX"
./states_creator.ps1 -FULL_STATE_NAME "Utah" -ABBREVIATED_STATE_NAME "UT"
./states_creator.ps1 -FULL_STATE_NAME "Vermont" -ABBREVIATED_STATE_NAME "VT"
./states_creator.ps1 -FULL_STATE_NAME "Virginia" -ABBREVIATED_STATE_NAME "VA"
./states_creator.ps1 -FULL_STATE_NAME "Washington" -ABBREVIATED_STATE_NAME "WA"
./states_creator.ps1 -FULL_STATE_NAME "West Virginia" -ABBREVIATED_STATE_NAME "WV"
./states_creator.ps1 -FULL_STATE_NAME "West Virginia" -ABBREVIATED_STATE_NAME "WI"
./states_creator.ps1 -FULL_STATE_NAME "Wyoming" -ABBREVIATED_STATE_NAME "WY"
./states_creator.ps1 -FULL_STATE_NAME "District of Columbia" -ABBREVIATED_STATE_NAME "DC"